name: ci

# Controls when the action will run. Triggers the workflow on push for any branch, and
# pull requests to master
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    # run the job on every combination of "os" above
    runs-on: ${{ matrix.os }}

    steps:
    - uses: conda-incubator/setup-miniconda@v2
      if: matrix.os == 'windows-latest'
      with:
        auto-update-conda: true

    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: |
        git config --global core.autocrlf false
        conda install -c conda-forge m2w64-gcc m2w64-zeromq
        echo "::set-env name=ROSWELL_INSTALL_DIR::$HOME/ros"
        echo "::add-path::$HOME/ros/bin"
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x

    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libzmq3-dev sbcl

    - name: Install MacOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install clozure-cl czmq sbcl

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Jupyter via pip
      if: matrix.os != 'windows-latest'
      run: |
        pip install --upgrade pip setuptools wheel jupyter jupyter_kernel_test
        jupyter --version

    - name: Install Jupyter via conda
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: |
        conda install -c conda-forge jupyterlab
        jupyter --version

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Quicklisp
      if: matrix.os != 'windows-latest'
      run: |
        curl -kLO https://beta.quicklisp.org/quicklisp.lisp

    - name: Setup source registry
      run: |
        mkdir -p $HOME/.config/common-lisp
        echo "(:source-registry (:tree (\"$PWD\")) :inherit-configuration)" >$HOME/.config/common-lisp/source-registry.conf

    - name: Clone shasht (only need when Quicklisp is out of date)
      run: |
        git clone https://github.com/yitzchak/shasht.git ~/quicklisp/local-projects/shasht

    - name: Install SBCL kernel via system
      if: matrix.os != 'windows-latest'
      run: |
        sbcl --non-interactive --load scripts/usr-install.lisp sbcl

    - name: Install SBCL kernel via roswell
      if: matrix.os == 'windows-latest'
      run: |
        ros install ./common-lisp-jupyter.asd

    - name: Install CCL kernel
      if: matrix.os == 'macos-latest'
      run: |
        ccl64 --batch --load scripts/usr-install.lisp

    # - name: Install ECL Jupyter kernel
    #   if: matrix.os == 'ubuntu-latest'
    #   run: |
    #     ecl -shell scripts/usr-install.lisp

    - name: Run kernel tests
      run: |
        python tests/client.py
