name: ci

# Controls when the action will run. Triggers the workflow on push for any branch, and
# pull requests to master
on:
  push:
    branches: [ master ]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest

    # run the job on every combination of "os" above
    runs-on: ${{ matrix.os }}

    steps:
    # tell git not to convert line endings
    # change roswell install dir and add it to path
    - name: Windows specific
      if: matrix.os == 'windows-latest'
      run: |
        git config --global core.autocrlf false
        echo "::set-env name=ROSWELL_INSTALL_DIR::$HOME/ros"
        echo "::add-path::$HOME/ros/bin"

    - name: Ubuntu specific
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libzmq3-dev sbcl

    - name: MacOs specific
      if: matrix.os == 'macos-latest'
      run: |
        brew install czmq scbl

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Jupyter and Quicklisp
      run: |
        pip install --upgrade pip setuptools wheel jupyter jupyter_kernel_test
        curl -kLO https://beta.quicklisp.org/quicklisp.lisp
        sbcl --non-interactive --load quicklisp.lisp \
             --eval '(quicklisp-quickstart:install)' \
             --eval '(ql-util:without-prompting (ql:add-to-init-file))'

    - name: System information
      run: |
        jupyter --version

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Jupyter kernels (CCL, SBCL)
      continue-on-error: true
      run: |
        sbcl --non-interactive --eval '(ql:quickload :ziz)' \
             --eval '(ziz:with-distribution (dist :releases '(".")) (ql-dist:install-dist (ziz:distribution-info-url dist) :prompt nil) (ql:quickload :common-lisp-jupyter))'
	sbcl --non-interactive --eval '(ql:quickload :common-lisp-jupyter)' --eval '(clj:install :use-implementation t)'
#        ros run --lisp ccl-bin --eval '(ql:quickload :common-lisp-jupyter)' --eval '(clj:roswell-install "ccl-bin")'

    # - name: Install Jupyter kernels (ECL)
    #   if: matrix.os == 'ubuntu-latest'
    #   run: |
    #     curl -kLO https://beta.quicklisp.org/quicklisp.lisp
    #     ecl -shell scripts/usr-install.lisp

    - name: Run kernel tests
      run: |
        python tests/client.py
