name: CI

# Controls when the action will run. Triggers the workflow on push for any branch, and
# pull requests to master
on:
  push:
    branches: [ master ]
  pull_request:

defaults:
  run:
    shell: bash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    # run the job on every combination of "lisp" and "os" above
    runs-on: ${{ matrix.os }}

    steps:
    # tell git not to convert line endings
    # change roswell install dir and add it to path
    - name: windows specific settings
      if: matrix.os == 'windows-latest'
      run: |
        git config --global core.autocrlf false
        echo "::set-env name=ROSWELL_INSTALL_DIR::$HOME/ros"
        echo "::add-path::$HOME/ros/bin"

    - name: ubuntu specific
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libzmq3-dev
        echo "$HOME/.roswell/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install jupyter
      run: pip install --upgrade pip setuptools wheel jupyter jupyter_kernel_test

    - name: install roswell
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh -x
        ros install ccl-bin

    - name: install code
      continue-on-error: true
      run: |
        ros install ./common-lisp-jupyter.asd
        ros run --lisp ccl-bin --eval '(ql:quickload :common-lisp-jupyter)' --eval '(clj:roswell-install "ccl-bin")'

    - name: load code and run tests
      run: python tests/client.py
