name: ci

# Controls when the action will run. Triggers the workflow on push for any branch, and
# pull requests to master
on:
  push:
    branches: [ master ]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        lisp:
        - sbcl-bin
        - ccl-bin
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    # run the job on every combination of "os" above
    runs-on: ${{ matrix.os }}

    steps:
    - uses: conda-incubator/setup-miniconda@v2
      if: matrix.os == 'windows-latest'
      with:
        auto-update-conda: true

    - name: Install Windows dependencies
      if: matrix.os == 'windows-latest'
      shell: bash -l {0}
      run: |
        git config --global core.autocrlf false
        conda install -c conda-forge m2w64-gcc m2w64-zeromq

    - name: Install Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libzmq3-dev

    - name: Install MacOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install czmq

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Jupyter
      run: |
        pip install --upgrade pip setuptools wheel jupyter jupyter_kernel_test
        jupyter --version

    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: 40ants/setup-lisp@v1

    - name: Install shasht git
      run: |
        ros install yitzchak/shasht

    - name: Install kernel
      run: |
        ros install common-lisp-jupyter.asd

    - name: Run kernel tests
      run: |
        python tests/client.py
